### ISSUE TITLE
Could you add a license, please?

### ISSUE THREAD

**Issue by jacmoe** [herrecito/engine#1]
I have been using your engine as a starting point for my own raycaster/retro engine, and I noticed that your repository does not have a license.

I would be happy if you could add a license to it, and I would be even happier if that license was permissive, like BSD, MIT or ISC.

Thanks :)

**Comment by herrecito** [comment]
Sure, do with it as you please ^^_

**Comment by jacmoe** [comment]
Thanks a lot ! 😃
Also, I really appreciate that you put your engine up on Github in the first place - it has been a great help :)
